### PR TITLE
Fix: Trim to be compatible with old versions

### PR DESCRIPTION
**Pull request by diamond-duke**
Some Nitaners are still using old versions. Forgot to trim()...

### CODE REVIEW

**Comment by 1dy** [comment]
lmao. I found mine is broken. Hopefully you have fully tested.

**Review by 1dy — APPROVED** [review]
I will approve this one. 
Could you please test this PR? 😉 
I will merge it after 1 hour

**Comment by diamond-duke** [comment]
Tested on my MacOS Sonoma:

1. Chrome: Works after PR1. Works after PR2.
2. Safari: Doesn't work after PR1. Works after PR2.
3. Firefox: Doesn't work after PR1. Works after PR2.

**Comment by 1dy** [comment]
Thank you so much! Nitan Hero.

💯

**Pull request merged**
